### PR TITLE
Backport PVC support to v0.5.2

### PR DESCRIPTION
**Pull request by shrutir25**
- implementing support for PV in v0.5.2  #1861
- do not merge as further testing is needed; opening PR to get review comments

### CODE REVIEW

**Comment by rjtsdl** [comment]
Overall LGTM, as long as you can get one successful run
1. you can just provision acs-engine k8s
2. when you create etcdcluster, add this into the pod definition.
```
  pod:
    persistentVolumeClaimSpec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 512Mi
      storageClassName: default
```

**Comment by rjtsdl** [comment]
I did some test, looks pv is working now.

```
NAME                             READY     STATUS    RESTARTS   AGE       IP             NODE
etcd-operator-668bbdc7bf-f4xq5   1/1       Running   0          7m        10.240.0.109   k8s-agent-40679128-1
example-etcd-cluster-0000        1/1       Running   0          7m        10.240.0.11    k8s-agent-40679128-2
example-etcd-cluster-0001        1/1       Running   0          4m        10.240.0.87    k8s-agent-40679128-0
example-etcd-cluster-0002        1/1       Running   0          2m        10.240.0.105   k8s-agent-40679128-1
NAME                    STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                      KERNEL-VERSION      CONTAINER-RUNTIME
k8s-agent-40679128-0    Ready     agent     17d       v1.8.7    <none>        Debian GNU/Linux 8 (jessie)   4.13.0-1005-azure   docker://1.12.6
k8s-agent-40679128-1    Ready     agent     17d       v1.8.7    <none>        Debian GNU/Linux 8 (jessie)   4.13.0-1005-azure   docker://1.12.6
k8s-agent-40679128-2    Ready     agent     17d       v1.8.7    <none>        Debian GNU/Linux 8 (jessie)   4.13.0-1005-azure   docker://1.12.6
k8s-master-40679128-0   Ready     master    17d       v1.8.7    <none>        Debian GNU/Linux 8 (jessie)   4.13.0-1005-azure   docker://1.12.6
show storageclass
NAME                 PROVISIONER
azurefile            kubernetes.io/azure-file
default (default)    kubernetes.io/azure-disk
etcd-backup-gce-pd   kubernetes.io/gce-pd
managed-premium      kubernetes.io/azure-disk
managed-standard     kubernetes.io/azure-disk
show pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                              STORAGECLASS   REASON    AGE
pvc-15d7068d-0d20-11e8-8ece-000d3af7b998   1Gi        RWO            Delete           Bound     v52apv/example-etcd-cluster-0001   default                  3m 
pvc-6ebff606-0d20-11e8-8ece-000d3af7b998   1Gi        RWO            Delete           Bound     v52apv/example-etcd-cluster-0002   default                  1m 
pvc-bf694680-0d1f-11e8-8ece-000d3af7b998   1Gi        RWO            Delete           Bound     v52apv/example-etcd-cluster-0000   default                  6m 
```

**Comment by shrutir25** [comment]
great ! lgtm

**Comment by rjtsdl** [comment]
`rjtsdl/etcd-operator:v0.5.2-azure-pv1` is the image

**Pull request merged**
